export interface Question {
  question: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: 'optionA' | 'optionB' | 'optionC' | 'optionD';
  infoQuest: string;
}

export const QUESTIONS: Question[] = [
  /////////////////////////////////مقدمه/////////////////////////////////////
  {
    question: ' يعتبر سفر اعمال الرسل من الاسفار ',
    optionA: 'الشعريه ',
    optionB: 'الانجيليه ',
    optionC: 'التاريخيه',
    optionD: 'النبويه',
    correctOption: 'optionC',
    infoQuest: 'مقدمه السفر',
  },
  {
    question: ' تكررت كلمه الروح القدس .......مره فالسفر ',
    optionA: ' 55',
    optionB: ' 66',
    optionC: '33',
    optionD: '44',
    correctOption: 'optionA',
    infoQuest: 'مقدمه السفر',
  },
  {
    question: ' الخريطه التي رسمها السيد المسيح للكرازه تبدا بمدينه ',
    optionA: 'بيت لحم ',
    optionB: 'اورشليم ',
    optionC: 'بيت عنيا',
    optionD: 'اليهوديه',
    correctOption: 'optionB',
    infoQuest: 'مقدمه السفر',
  },
  {
    question: ' اول كنيسه امميه هي كنيسه ',
    optionA: 'افسس ',
    optionB: ' روما',
    optionC: 'انطاكيه',
    optionD: 'كولوسي',
    correctOption: 'optionC',
    infoQuest: 'مقدمه السفر',
  },
  {
    question: ' تحدث القديس لوقا عن حريق روما في سفر اعمال الرسل ',
    optionA: 'صح ',
    optionB: 'خطا ',
    optionC: '',
    optionD: '',
    correctOption: 'optionB',
    infoQuest: 'مقدمه السفر',
  },
  {
    question: ' انضم لوقا لبولس في الرحله التبشيريه  ',
    optionA: ' الثالثه',
    optionB: ' الثانيه',
    optionC: 'الي روما',
    optionD: 'الاولي',
    correctOption: 'optionB',
    infoQuest: 'مقدمه السفر',
  },
  {
    question: '  انضم لوقا لبولس الرسول في مدينه ',
    optionA: 'ترواس ',
    optionB: 'انطاكيه ',
    optionC: 'فيلبي',
    optionD: 'افسس',
    correctOption: 'optionA',
    infoQuest: 'مقدمه السفر',
  },
  {
    question: ' كتب لوقا انجيله وسفرالاعمال باللغه ',
    optionA: ' الارميه',
    optionB: 'اليونانيه ',
    optionC: 'العبريه',
    optionD: 'الاتينيه',
    correctOption: 'optionB',
    infoQuest: 'مقدمه السفر',
  },
  {
    question: ' يظن ان القديس لوقا ولد في ',
    optionA: 'روما ',
    optionB: 'انطاكيا ',
    optionC: 'ترواس',
    optionD: 'اورشليم',
    correctOption: 'optionB',
    infoQuest: 'مقدمه السفر',
  },
  {
    question: ' الفكره الرئيسيه للسفر هي ',
    optionA: 'استشهاد اسطفانوس ',
    optionB: 'انتشار الكنيسه في العالم ',
    optionC: 'خدمه بطرس',
    optionD: 'ايمان كنيسه روما',
    correctOption: 'optionB',
    infoQuest: 'مقدمه السفر',
  },

  /////////////////////////////////1-4/////////////////////////////////////
  {
    question:
      '<img id="myImg" src="img/111.png" alt="Snow" style="width:200px; height: 150px; ">',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest:
      ' مريم محروس وفيولا عمادالايه هي (لان يوحنا عمد بالماء؛ اما انتم فستتعمدون بالروح القدس، ليس بعد هذه الايام بكثير)    ',
  },
  {
    question:
      '<img id="myImg" src="img/333.png" alt="Snow" style="width:200px; height: 150px; ">',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest:
      'مريم محروس وفيولا عمادالايه اهه(فقال لهم ليس لكم ان تعرفوا الازمنه والاوقات التي جعلها الرب في سلطانه لكنكم ستنالون قوه متي حل الروح القدس عليكم وتكونون لي شهودا في اورشليم وفي كل اليهوديه والسامره وإلي اقصي الارض)            ',
  },
  {
    question:
      ' لأَنَّ يُوحَنَّا عَمَّدَ ........... ، وَأَمَّا أَنْتُمْ فَسَتَتَعَمَّدُونَ بِالرُّوحِ الْقُدُسِ ، لَيْسَ بَعْدَ هذِهِ الأَيَّامِ بِكَثِيرٍ',
    optionA: 'بالماء',
    optionB: 'بالعنب',
    optionC: 'بالنار',
    optionD: 'بالروح القدس',
    correctOption: 'optionA',
    infoQuest: 'مريم محروس وفيولا عماد',
  },
  {
    question:
      ' هولاء كلهم كانوا يواظبون بنفس واحدة علي الصلاة والطمبة ، مع النساء ، ومريم ........... ، ومع أخوتو',
    optionA: 'أخت مرثا',
    optionB: 'أخت لعازر',
    optionC: 'أم يسوع',
    optionD: 'المجدلية',
    correctOption: 'optionC',
    infoQuest: 'مريم محروس وفيولا عماد',
  },
  {
    question: 'ولما حضر يوم .......... كان الجميع معا بنفس واحدة',
    optionA: 'الستين',
    optionB: 'الأربعين',
    optionC: 'الخمسين',
    optionD: 'المئة',
    correctOption: 'optionC',
    infoQuest: 'مريم محروس وفيولا عماد',
  },
  {
    question:
      'لأ ن .......... يقول فيو : كنت أرى الرب أمامى فى كل حين ، إنو عن يمينى ، لكى لا أتزعزع ',
    optionA: 'بطرس',
    optionB: 'يعقوب',
    optionC: 'يوحنا',
    optionD: 'داود',
    correctOption: 'optionD',
    infoQuest: 'مريم محروس وفيولا عماد',
  },
  {
    question: 'فقبموا كلامو بفرح ، واعتمدوا ، وانضم فى ذلك الي وم نحو ............. نفس ',
    optionA: 'ثلاثة آلاف',
    optionB: 'أربعة آلاف',
    optionC: 'مئة',
    optionD: 'خمسة آلاف',
    correctOption: 'optionA',
    infoQuest: 'مريم محروس وفيولا عماد',
  },
  {
    question:
      ' وبينما كان الرجل .......... الذى شُفى متمسكاً ببطرس ويوحنا ، تراكض اليهم جميع الشعب إلى الرواق الذى يقال له  رواق سميمان  وهم مندىشون',
    optionA: 'الأعمى',
    optionB: 'الأصم',
    optionC: 'الخاطئ',
    optionD: 'الأعرج',
    correctOption: 'optionD',
    infoQuest: 'مريم محروس وفيولا عماد',
  },
  {
    question:
      ' فإن ........ قال للآباء : إن نبياً مثلى سيقيم لكم الرب اليكم من أخوتكم . لو تسمعون فى كل ما يكلمكم به',
    optionA: 'موسى',
    optionB: 'يعقوب',
    optionC: 'إسحاق',
    optionD: 'يوحنا',
    correctOption: 'optionA',
    infoQuest: 'مريم محروس وفيولا عماد',
  },
  {
    question:
      'ويوسف الذى دعى من الرسل .......... ، الذى يترجم ابن الوعظ ، وىو لا وى قبرسى الجنس ',
    optionA: 'توما',
    optionB: 'إيميا',
    optionC: 'متى',
    optionD: 'برنابا',
    correctOption: 'optionD',
    infoQuest: 'مريم محروس وفيولا عماد',
  },
  {
    question:
      ' فمما سمعوا ، رفعوا بنفس اوحدة صوتاً إلى الله . وقالوا : أيها السيد . أنت هو الإ له الصانع السماء والأ رض والبحر وكل ما فيها ، القائل بفم .......... فتاك : لماذا ارتجت الأمم وتفكر الشعوب بالباطل ؟',
    optionA: 'متى',
    optionB: 'بطرس',
    optionC: 'توما',
    optionD: 'داود',
    correctOption: 'optionD',
    infoQuest: 'مريم محروس وفيولا عماد',
  },
  {
    question: '  يُقرأ فصل من سفر أعمال الرسل في القداس الإلهي ويسمي   ',
    optionA: 'البولس',
    optionB: 'الكاثوليكون',
    optionC: 'الإبركسيس ',
    optionD: 'السنكسار',
    correctOption: 'optionC',
    infoQuest: 'مريم محروس وفيولا عماد',
  },
  {
    question: '   حل الروو القدس على التلاميذ في الساعة ........ من النهار. ',
    optionA: 'الثالثة',
    optionB: 'السادسة',
    optionC: 'التاسعة ',
    optionD: 'الحادية عشر',
    correctOption: 'optionA',
    infoQuest: 'مريم محروس وفيولا عماد',
  },
  {
    question: 'طلب امعرج من الرسوحن أن',
    optionA: 'يمنحاه الشفاء',
    optionB: 'يعطياه صدقة',
    optionC: ' يحملاه داخل الهيكل',
    optionD: 'كل ما سبق',
    correctOption: 'optionB',
    infoQuest: 'مريم محروس وفيولا عماد',
  },
  {
    question: 'اذكر النبوه: لِذلِكَ سُرَّ قَلْبِي وَتَهَلَّلَ لِسَانِي. حَتَّى جَسَدِي أَيْضًا سَيَسْكُنُ عَلَى رَجَاءٍ.',
    optionA: 'الاجابه صح ',
    optionB: ' الاجابه غلط',
    optionC: '',
    optionD: ' ',
    correctOption: 'optionA',
    infoQuest: 'مريم محروس وفيولا عماد الاجابه هي(مز16-11-8)',
  },
  {
    question: 'استشهاد القديس لوقاا',
    optionA: 'الاجابه صح ',
    optionB: ' الاجابه غلط',
    optionC: '',
    optionD: ' ',
    correctOption: 'optionA',
    infoQuest: 'مريم محروس وفيولا عماد الاجابه هي(22 بابه)',
  },
  {
    question: ' توما الرسول',
    optionA: 'الاجابه صح ',
    optionB: ' الاجابه غلط',
    optionC: '',
    optionD: ' ',
    correctOption: 'optionA',
    infoQuest: 'مريم محروس وفيولا عماد الاجابه هي(26 بشنس )',
  },
  {
    question: ' كلمه الموعد الثاني يقصد بها ',
    optionA: '  المجى الاول ',
    optionB: ' المعموديه ',
    optionC: 'حلول الروح القدس',
    optionD: ' المجي الثاني',
    correctOption: 'optionC',
    infoQuest: 'مريم محروس وفيولا عماد  ',
  },
  {
    question: ' جميع التلاميذ من الجليل ماعادا  ',
    optionA: ' يهوذا الاسخريوطي ',
    optionB: ' توما ',
    optionC: 'متي',
    optionD: ' يعقوب',
    correctOption: 'optionA',
    infoQuest: 'مريم محروس وفيولا عماد  ',
  },
  {
    question: ' المقصود ب قد امتلاوا سلافه ',
    optionA: ' كلمات تشجيع الحاضرين ',
    optionB: ' انبهار بما حدث ',
    optionC: 'تساول عما حدث',
    optionD: 'الاستهزاء من الاباء الرسل واتهامهم بالسكر ',
    correctOption: 'optionD',
    infoQuest: 'مريم محروس وفيولا عماد  ',
  },
  {
    question: ' من هو الذي اعاد بناء هيكل سليمان ',
    optionA: 'داود  ',
    optionB: ' زربابل ',
    optionC: 'نحميا',
    optionD: ' سليمان',
    correctOption: 'optionB',
    infoQuest: 'مريم محروس وفيولا عماد  ',
  },
  {
    question: ' كان جند الهيكل من سبط ...... او من جنود الرومان ',
    optionA: ' افرايم ',
    optionB: ' يهوذا ',
    optionC: 'لاوي',
    optionD: ' بنيامين',
    correctOption: 'optionC',
    infoQuest: 'مريم محروس وفيولا عماد  ',
  },

  /////////////////////////////////5-8/////////////////////////////////////
  {
    question: '  اول مرة تُذكر كلمة الكنيسة في سفر أعمال الرسل كانت بعد ..... مباشر.',
    optionA: 'شفاء الأعرج',
    optionB: 'حلول الروح القدس',
    optionC: 'اختيار متياس الرسول ',
    optionD: 'موت حنانيا وسفيره',
    correctOption: 'optionD',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question: '  طريقة اقامة الشمامسة حسب ما حددها سفر أعمال الرسل تكون ب    ',
    optionA: 'الانتخاب فقط',
    optionB: 'التعيين من الرسل',
    optionC: 'الانتخاب ووضع أيدي الرسل ',
    optionD: 'تعيين الرسل ووضع أيديهم',
    correctOption: 'optionC',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question: ' أرسل يوسف واستدعى أبوه يعقوب اسرائيل وكل عشيرت وكانوا حوالي .... نفس.',
    optionA: '75',
    optionB: '100',
    optionC: ' 200',
    optionD: '300',
    correctOption: 'optionA',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question: 'أول شهيد في المسيحية ذكر سفر أعمال الرسل انه استشهد',
    optionA: 'مصلوبا',
    optionB: 'مذبوحا',
    optionC: ' رجما',
    optionD: 'غرقا',
    correctOption: 'optionC',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question:
      '  سجود الوزير في اورشليم وقراءته في النبوة، يدلان على أن مع كونه حبشياً لكنه   ',
    optionA: 'وثنياً',
    optionB: 'بوذياً',
    optionC: 'متهوداً ',
    optionD: 'لا شئ مما سبق صحيح',
    correctOption: 'optionC',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question: ' العلامة المميزة التي ظهرت على وزير الحبشة بعد عماده هي',
    optionA: 'التكلم بألسنة',
    optionB: 'الفرح',
    optionC: 'التسبيح ',
    optionD: 'كل ما سبق',
    correctOption: 'optionB',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question:
      ' ورجل اسمو .......... ، وامراته سفيرة ، باع ملكا واختمس من الثمن ، وامراته لها خبر ذلك ، وأتى بجزء ووضعو عن أرجل الرسل',
    optionA: 'بطرس',
    optionB: 'متى',
    optionC: 'توما',
    optionD: 'حنانيا',
    correctOption: 'optionD',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question:
      'لأ نو قبل ىذه الأيام قاد ثوداس قائلا عن نفسو أنو شئ ، الذى التصق بو عدد من الرجاب نحو .......... ، الذى قتل ، وجميع الذى انقادوا إليو تبددوا وصاروا كلا لا شئ ',
    optionA: 'خمسمائة',
    optionB: 'ثلاثمائة',
    optionC: 'سبعمائة',
    optionD: 'أربعمائة',
    correctOption: 'optionD',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question: ' ثم حدث بعد مدة نحو ........ ساعات ، أن امراته دخمت ، وليس ليا خبر ما جرى',
    optionA: 'ست',
    optionB: 'ثلاث',
    optionC: 'خمس',
    optionD: 'تسع',
    correctOption: 'optionB',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question:
      ' وفى تمك الأيام إذ تكاثر التلاميذ ، حدث تذمر من ........ عمى العبرانيين أن أرملهم كن يغفل عنين الخدمة اليومية',
    optionA: 'اليونانيين',
    optionB: 'الجميميين',
    optionC: 'اليهود',
    optionD: 'الفريسيين',
    correctOption: 'optionA',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question:
      ' وتكمم الله ىكذا : أن يكون نسله متغرباً فى أرض غريبة ، فيستبعدوه ويسيئوا إليو .......... سنة',
    optionA: 'أربع مئة',
    optionB: 'ثلاث مئة',
    optionC: 'مئة',
    optionD: 'خمس مئة',
    correctOption: 'optionA',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question:
      ' وأعطاه عيد الختان ، وهكذا ولد اسحاق وختنو فى اليوم ........... واسحاق ولد يعقوب ، ويعقوب ولد رؤساء الآباء الاثنى عشر',
    optionA: 'التاسع',
    optionB: 'الثامن',
    optionC: 'الخامس',
    optionD: ' الرابع ',
    correctOption: 'optionB',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question:
      ' وكان قبلا فى المدينة رجل اسمو ............ ، يستعمل السحر ويدىش شعب السامرة ، قائلا انه شئ عظيم',
    optionA: 'بطرس',
    optionB: 'يعقوب',
    optionC: 'سيمون',
    optionD: 'توما',
    correctOption: 'optionC',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question:
      ' ثم أن ملاك الرب كلم ........... قائلا :  قم واذىب نحو الجنوب ، على الطريق المنحدرة من أورشميم إلى غزة التى هى برية',
    optionA: 'توما',
    optionB: 'بطرس',
    optionC: 'إندراوس',
    optionD: 'فيلبس',
    correctOption: 'optionD',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question: 'نياحه القديس كرنيليوس قائد المئه ',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: 'مريم عماد و نانسي ناصر الاجابه هي (23هاتور)',
  },
  {
    question: 'متي',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: 'مريم عماد و نانسي ناصر الاجابه هي (12 بابا)',
  },
  {
    question: 'من قائل العباره:ان كان حقا امام الله ان نسمع لكم اكثر من الله فاحكمو ',
    optionA: 'بطرس فقط',
    optionB: 'يوحنا فقط',
    optionC: 'بطرس ويوحنا',
    optionD: 'برنابا',
    correctOption: 'optionC',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question: 'برنابا يتصف بكل ما يلي ماعدا انه ',
    optionA: 'ابن الواعظ',
    optionB: 'ولد في اورشليم',
    optionC: 'يوسف',
    optionD: 'لاوي',
    correctOption: 'optionB',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },
  {
    question: ' الذي حكم علي حنانيا وسفيرههو',
    optionA: 'بولس',
    optionB: 'يوحنا ',
    optionC: 'الروح القدس',
    optionD: 'بطرس',
    correctOption: 'optionC',
    infoQuest: 'مريم عماد و نانسي ناصر',
  },

  /////////////////////////////////9-12/////////////////////////////////////
  {
    question:
      '<img id="myImg" src="img/222.png" alt="Snow" style="width:200px; height: 150px; ">',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest:
      'مريم حليم واوجيني اشرف الايه اهه (فقال لهم ها انا انظر السموات مفتوحه وابن الانسان قائماً عن يمين الله)   ',
  },
  {
    question:
      '<img id="myImg" src="img/444.png" alt="Snow" style="width:200px; height: 150px; ">',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest:
      'مريم حليم واوجيني اشرف الايه اهه (ثم جثا علي ركبتيه وصرخ بصوت عظيم يارب لا تقم لهم هذه الخطيه واذ قال هذا رقد  )   ',
  },
  {
    question:
      'فأخذ ...... شاول وأحضره الي الرسل، وحذسهم كيف أبصر الرب في الطريق وكيف جاهر في دمشق باسم يسوع.',
    optionA: 'برنابا',
    optionB: 'فيلبس',
    optionC: 'بطرس',
    optionD: 'حنانيا',
    correctOption: 'optionA',
    infoQuest: 'مريم حليم واوجيني اشرف     ',
  },
  {
    question: ' كان في قيصرية رجل اسم كرويليوس كان يعمل في',
    optionA: 'القصر',
    optionB: 'المجمع',
    optionC: 'الجيش ',
    optionD: 'الهيكل',
    correctOption: 'optionC',
    infoQuest: 'مريم حليم واوجيني اشرف     ',
  },
  {
    question: '  أول تلميذ استشهد من تلاميذ السيد المسيح كان ',
    optionA: 'يعقوب بن زبدي',
    optionB: 'يعقوب بن حلفى',
    optionC: ' يوحنا المعمدان',
    optionD: 'يوحنا بن زبدي',
    correctOption: 'optionA',
    infoQuest: 'مريم حليم واوجيني اشرف     ',
  },
  {
    question: 'ماذا فعم هيرودس بعد معجزة خروج بطرس الرسوول من السجن ؟',
    optionA: 'آمن بالمسيح',
    optionB: 'أرسل يقبض عليه ثانية',
    optionC: ' أمر بقتل الحراس',
    optionD: 'تعجب وإندهش',
    correctOption: 'optionC',
    infoQuest: 'مريم حليم واوجيني اشرف     ',
  },
  {
    question:
      '  اذكر النبوه: وَأَمَّا أَنَا فَأَقُولُ لَكُمْ: لاَ تُقَاوِمُوا الشَّرَّ، بَلْ مَنْ لَطَمَكَ عَلَى خَدِّكَ الأَيْمَنِ فَحَوِّلْ لَهُ الآخَرَ أَيْضًا.',
    optionA: 'الاجابه صح ',
    optionB: ' الاجابه غلط',
    optionC: '',
    optionD: ' ',
    correctOption: 'optionA',
    infoQuest: 'مريم حليم واوجيني اشرفا الاجابه هي(اش 10:8)     ',
  },
  {
    question: ' استشهاد القديس استفانوس',
    optionA: 'الاجابه صح ',
    optionB: ' الاجابه غلط',
    optionC: '',
    optionD: ' ',
    correctOption: 'optionA',
    infoQuest: 'مريم حليم واوجيني اشرفا الاجابه هي(1 طوبه)     ',
  },
  {
    question: '   سمعان الغيور',
    optionA: 'الاجابه صح ',
    optionB: ' الاجابه غلط',
    optionC: '',
    optionD: ' ',
    correctOption: 'optionA',
    infoQuest: 'مريم حليم واوجيني اشرفا الاجابه هي(15 بشنس )     ',
  },
  {
    question: '  قام ببناء مدينه القيصريه  ',
    optionA: ' القيصر ',
    optionB: ' نبوخذ نصر ',
    optionC: 'هيرودس الكبير',
    optionD: 'كورش الملك ',
    correctOption: 'optionC',
    infoQuest: 'مريم حليم واوجيني اشرفا    ',
  },
  {
    question: 'كم مره ذكر قبول الله لصلوات وصدقات كرنيليوس في الاصحاح العاشر',
    optionA: ' 1 ',
    optionB: ' 2  ',
    optionC: '3 ',
    optionD: ' 4 ',
    correctOption: 'optionB',
    infoQuest: 'مريم حليم واوجيني اشرفا    ',
  },

  /////////////////////////////////13-16/////////////////////////////////////
  {
    question: '🗣🚶🏻‍♂👉🏺🙇🏻‍♂✝🤴🏻👥🇮🇱 ',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest:
      'شادي خليفه وشنوده ماهرالايه اهه(فقالـ له الرب: اذهب لان هذا لي اناء مختار ليحمل اسمي امام امم وملوك بني اسرائيل)   ',
  },
  {
    question: '🐑🫴🔪🤐✂.. ❌🤐 ',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest:
      'شادي خليفه وشنوده ماهرالايه اهه(مثل شاه سيق إلي الذبح ومثل خروف صامت امام الذي يجزه هكذا لم يفتح فاه)   ',
  },
  {
    question: ' من انا؟ نبي كاذب يهودي يقيم في جزيرة قبرص',
    optionA: 'الاجابه صح',
    optionB: 'الاجابه غلط',
    optionC: ' ',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: 'شادي خليفه وشنوده ماهر ',
  },
  {
    question: ' البليد التيي خرج منها القديسان بولس وبرنابا ونفضا غبار أرجلهما عليهم هي',
    optionA: 'ايقونية',
    optionB: 'بيسدية',
    optionC: 'انطاكيه ',
    optionD: 'لستره',
    correctOption: 'optionC',
    infoQuest: 'شادي خليفه وشنوده ماهر ',
  },
  {
    question: ' في لسترة نال بولس الرسول',
    optionA: 'التكريم من الوثنيين',
    optionB: 'الرجم من اليهود',
    optionC: 'الإجابتان صحيحتان',
    optionD: 'الإجابتان خاطئتان',
    correctOption: 'optionA',
    infoQuest: 'شادي خليفه وشنوده ماهر ',
  },
  {
    question: 'عندما أراد كاهن زفس أن يكلل بولس وبرنابا ويذبح لهما الثيران',
    optionA: 'فرحا بالروح',
    optionB: 'خلعا أحذيتهما',
    optionC: 'مزقا ملابسهما ',
    optionD: 'شكرا الرب',
    correctOption: 'optionC',
    infoQuest: 'شادي خليفه وشنوده ماهر ',
  },
  {
    question: 'لماذا لم يصطحب بولس الرسول القديس مرقس في رحلته التبشيرية الثانية؟',
    optionA: 'لأنه من أصل أممي',
    optionB: 'لأنه لم يكمل معه الرحلة الأولى',
    optionC: ' لكبر سنه',
    optionD: 'جميع ما سبق',
    correctOption: 'optionB',
    infoQuest: 'شادي خليفه وشنوده ماهر ',
  },
  {
    question: '"اعبر الى مكدونية وأعنا" قيلت ل',
    optionA: 'بولس',
    optionB: 'شاول',
    optionC: 'يوحنا',
    optionD: 'تيموثاوس',
    correctOption: 'optionA',
    infoQuest: 'شادي خليفه وشنوده ماهر ',
  },
  {
    question: ' أول من امن  بالسيد المسيح في مدينة فيلبي هي ',
    optionA: 'طابيثا',
    optionB: 'بريسكلا',
    optionC: 'روديا',
    optionD: 'ليدية',
    correctOption: 'optionD',
    infoQuest: 'شادي خليفه وشنوده ماهر ',
  },
  {
    question: 'تيموثاوس تلميذ بولس ',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: 'شادي خليفه وشنوده ماهرالاجابه اهه(23 طوبه)   ',
  },

  /////////////////////////////////17-20/////////////////////////////////////
  {
    question: ' 👌✍🙇🏻‍♂🪵🪦☝🔃⚰ ',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest:
      'مريم  مدحت ومارتن ناصر الايه اهه(ولما تمموا كل ما كتب عنه انزلوه عن الخشبه ووضعوه في قبر لكن الله اقامه من الاموات)  ',
  },
  {
    question: ' ☝❌👀😇.. 🫴⛈⏱🍒... 🫀😃 ',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest:
      'مريم  مدحت ومارتن ناصر الايه اهه(مع انه لم يترك نفسه بلا شاهد وهو يفعل خيرا: يعطينا من السماء امطارا وازمنه مثمره ويملا قلوبنا طعاماً وسرورا)  ',
  },
  {
    question: 'ذكر سفر أعمال الرسل أن سكان أثينا كانوا شغوفين ب',
    optionA: 'مناقشة الأفكار الجديدة',
    optionB: 'محبة المال الشديدة',
    optionC: 'تجارة البضائع الغالية',
    optionD: 'لا شئ مما سبق',
    correctOption: 'optionA',
    infoQuest: 'مريم  مدحت ومارتن ناصر',
  },
  {
    question: 'كان اسكندري الجنس، يهودي، فصيح، مقتدر في الكتب ، حار بالروح، مؤمن بالمسيح، هو',
    optionA: 'كرنيليوس',
    optionB: 'أبُلّوس',
    optionC: 'فيلبس',
    optionD: 'أغابوس',
    correctOption: 'optionB',
    infoQuest: 'مريم  مدحت ومارتن ناصر',
  },
  {
    question: ' هيج ديمتريوس أهل أفسس ضد بولس الرسوو لأن مكسبه سينعدم من ',
    optionA: 'السحر',
    optionB: 'معرفة الغيب',
    optionC: 'صناعة التماثيل',
    optionD: 'إخراج الشياطين',
    correctOption: 'optionC',
    infoQuest: 'مريم  مدحت ومارتن ناصر',
  },
  {
    question: 'قدم بولس الرسوو نموذجاً في الخدمذة لقسوس أفسس ، ولنا جميعاً، في أنه ظل يخدمهم',
    optionA: 'ثلاث سنوات',
    optionB: 'ليلاً ونهاراً',
    optionC: 'دون فتور',
    optionD: 'كل ما سبق',
    correctOption: 'optionD',
    infoQuest: 'مريم  مدحت ومارتن ناصر',
  },
  {
    question: ' اعلن بولس الرسول لقسوس افسس انه كان يعمل بايديه ل ',
    optionA: 'سد احتياجاته',
    optionB: 'سد احتياجات الذين يخدمون معه',
    optionC: 'لأن ليس له الحق في أخذ مقابل عن خدمته',
    optionD: 'أ ، ب معا',
    correctOption: 'optionD',
    infoQuest: 'مريم  مدحت ومارتن ناصر',
  },
  {
    question: 'استفانوس نقل جسد ',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خاطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: 'مريم  مدحت ومارتن ناصر الاجابه هي (15 توت)',
  },
  {
    question: 'يهوذا اخو الرب ',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خاطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: 'مريم  مدحت ومارتن ناصر الاجابه هي (25 بوونه)',
  },
  {
    question: 'اندراوس الرسول ',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خاطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: 'مريم  مدحت ومارتن ناصر الاجابه هي (4 كيهك)',
  },

  /////////////////////////////////21-24/////////////////////////////////////
  {
    question: '❌😨☝🗣🙋‍♂🫂❌🤕🙌👥🏙',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest:
      'مريم عطيه وياسمين عادل الايه اهه(لا تخف بل تكلم ولا تسكت لاني انا معك ولا يقع بك احد ليؤذيك لان لي شعبا كثيرا في هذه المدينه)  ',
  },
  {
    question: 'م هو الرجل الذي أخذ منطقة بولس وربط نفسه؟',
    optionA: 'الملك أغريباس',
    optionB: 'أغابوس النبي',
    optionC: 'الرسول غايس',
    optionD: 'أكيلا',
    correctOption: 'optionB',
    infoQuest: 'مريم عطيه وياسمين عادل',
  },
  {
    question: '"وَاضْطهَدْتُ هذَا الاَّطرِيقَ حَتَّى الْمَوْ ت". يقصد بهذا الطريق',
    optionA: 'المسيحية',
    optionB: 'عبادة الاصنام',
    optionC: 'اليهودية',
    optionD: 'الاوثان',
    correctOption: 'optionA',
    infoQuest: 'مريم عطيه وياسمين عادل',
  },
  {
    question: 'الصدوقيين هم ',
    optionA: 'جماعة يهودية',
    optionB: 'جماعة من الأمم',
    optionC: 'لا يؤمنوا بقيامة الاموات',
    optionD: 'أ ، ج معا',
    correctOption: 'optionD',
    infoQuest: 'مريم عطيه وياسمين عادل',
  },
  {
    question: 'كان اليهود يريدون الامير أن يحضر بولس اليهم ل',
    optionA: 'يحاوروه',
    optionB: 'يشتكوا عليه',
    optionC: 'يقتلوه',
    optionD: 'يعذبوه',
    correctOption: 'optionC',
    infoQuest: 'مريم عطيه وياسمين عادل',
  },
  {
    question: 'وصف اليهود المشتكين على بولس الديانة المسيحية بأنها',
    optionA: 'سريعة الانتشار',
    optionB: 'صحيحة',
    optionC: 'شيعة',
    optionD: 'سليمة',
    correctOption: 'optionC',
    infoQuest: 'مريم عطيه وياسمين عادل',
  },
  {
    question:
      'اذكر النبوه: سَأَرْجعُ بَعْدَ هذَا وَأَبْنِي أَيْضًا خَيْمَةَ دَاوُدَ السَّاقِطَةَ، وَأَبْنِي أَيْضًا رَدْمَهَا وَأُقِيمُهَا ثَانِيَةً،',
    optionA: 'الاجابه صح ',
    optionB: ' الاجابه غلط',
    optionC: '',
    optionD: ' ',
    correctOption: 'optionA',
    infoQuest: 'مريم عطيه وياسمين عادل الاجابه هي (عاموس 9-12:11)',
  },
  {
    question: 'استشهاد بطرس وبولس',
    optionA: 'الاجابه صح ',
    optionB: ' الاجابه غلط',
    optionC: '',
    optionD: ' ',
    correctOption: 'optionA',
    infoQuest: 'مريم عطيه وياسمين عادل الاجابه هي ( 15 ابيب)',
  },
  {
    question: 'متياس الرسول',
    optionA: 'الاجابه صح ',
    optionB: ' الاجابه غلط',
    optionC: '',
    optionD: ' ',
    correctOption: 'optionA',
    infoQuest: 'مريم عطيه وياسمين عادل الاجابه هي (8 برمهات)',
  },

  /////////////////////////////////25-28/////////////////////////////////////
  {
    question: ' 🗣⁉😭💔🙋‍♂✊🪢☝⚰✝ ',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest:
      'بهاء مجدي وساندس ناجح الايه اهه(فاجاب بولس: ماذا تفعلون؟ تبكون وتكسرون قلبي انني مستعد ليس ان اربط فقط بل ان اموت ايضا في اورشليم من اجل اسم الرب يسوع) ',
  },
  {
    question: ' متي',
    optionA: 'الاجابه صح',
    optionB: 'الاجابه غلط',
    optionC: '',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: 'بهاء مجدي وساندس ناجح  الاجابه هي (12 بابه)',
  },
  {
    question: ' طلب بولس الرسول من فستوس الوالي أن يحاكم امام  ',
    optionA: 'الأمير',
    optionB: 'اليهود',
    optionC: 'القيصر',
    optionD: 'رئيس الكهنة',
    correctOption: 'optionC',
    infoQuest: 'بهاء مجدي وساندس ناجح  ',
  },
  {
    question: 'عرض الوالي فستوس قضيية بولس الرسول على الملك ............ ليأخيذ رأيه فيها.',
    optionA: 'أغريباس',
    optionB: 'برنيكي',
    optionC: 'ترتلس',
    optionD: 'فيلكس',
    correctOption: 'optionA',
    infoQuest: 'بهاء مجدي وساندس ناجح  ',
  },
  {
    question: 'الملك أغريباس كان ................ مشاكل اليهود وعادتهم',
    optionA: 'يعرف',
    optionB: 'لا يفهم',
    optionC: 'لا يعلم',
    optionD: 'اجابة اخري',
    correctOption: 'optionA',
    infoQuest: 'بهاء مجدي وساندس ناجح  ',
  },
  {
    question: 'والآن أنا واقف أحاكم على رجاء الوعد الذي صار من الله لآبائنا. الوعيد  هو',
    optionA: 'القيامة',
    optionB: 'مجئ المسيح',
    optionC: 'تحرير أورشليم',
    optionD: 'ب ، ج معا',
    correctOption: 'optionB',
    infoQuest: 'بهاء مجدي وساندس ناجح  ',
  },
  {
    question: 'بعد أن سمع فستوس عن القيامة ظن الوالي بولس الرسول',
    optionA: 'يكذب',
    optionB: 'يهذي',
    optionC: 'يصدق',
    optionD: 'يقنعه بالايمان',
    correctOption: 'optionB',
    infoQuest: 'بهاء مجدي وساندس ناجح  ',
  },
  {
    question: 'كان قائد المئة يوليوس يعامل بولس معاملة',
    optionA: 'قوية',
    optionB: 'صعبة',
    optionC: 'أ، ب معا',
    optionD: 'جيدة',
    correctOption: 'optionD',
    infoQuest: 'بهاء مجدي وساندس ناجح  ',
  },
  {
    question: 'وقت العاصفة وقرب وصول السفينة للشاط خاف العسكر من',
    optionA: 'تحطم السفينة',
    optionB: 'هروب الأسري',
    optionC: 'قوة العاصفة',
    optionD: 'قلة الطعام',
    correctOption: 'optionB',
    infoQuest: 'بهاء مجدي وساندس ناجح  ',
  },
  {
    question: 'كان عدد الذين كانوا في السفينة ............ نفس',
    optionA: '277',
    optionB: '278',
    optionC: '200',
    optionD: '276',
    correctOption: 'optionD',
    infoQuest: 'بهاء مجدي وساندس ناجح  ',
  },
  {
    question: 'ظن البرابر بولس الرسول أنه ......... عندما نشبت الافعي  في يده.',
    optionA: 'سئ الحظ',
    optionB: 'قوي',
    optionC: 'قاتل',
    optionD: 'حكيم',
    correctOption: 'optionC',
    infoQuest: 'بهاء مجدي وساندس ناجح  ',
  },
  {
    question: 'ستسمعون سمعاً ولا تفهمون وستنظرون نظرا ولا تبصرون. قيل هذا عن',
    optionA: 'عدم السمع',
    optionB: 'عدم الفهم',
    optionC: 'عدم النظر',
    optionD: 'عدم الايمان',
    correctOption: 'optionD',
    infoQuest: 'بهاء مجدي وساندس ناجح  ',
  },
  {
    question: 'كانت نتيجة كلام بولس الرسول عن المسيحية أن اليهود',
    optionA: 'بعضهم اقتنع',
    optionB: 'لم يقتنعوا',
    optionC: 'جميعهم اقتنعوا',
    optionD: 'آمنوا جميعا',
    correctOption: 'optionA',
    infoQuest: 'بهاء مجدي وساندس ناجح  ',
  },

  /////////////////////////////////----/////////////////////////////////////
  {
    question:
      '<img id="myImg" src="img/1.jpg" alt="Snow" style="width:200px; height: 150px; ">',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: ' ',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: '(3+4=7)متنوع',
  },
  {
    question:
      '<img id="myImg" src="img/2.jpg" alt="Snow" style="width:200px; height: 150px; ">',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: ' ',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: '(5+3=8)متنوع',
  },
  {
    question:
      '<img id="myImg" src="img/3.jpg" alt="Snow" style="width:200px; height: 150px; ">',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: ' ',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: '(8-3=5)متنوع',
  },
  {
    question:
      '<img id="myImg" src="img/4.jpg" alt="Snow" style="width:200px; height: 150px; ">',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: ' ',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: '(8+0+1=9)متنوع',
  },
  {
    question:
      '<img id="myImg" src="img/5.jpg" alt="Snow" style="width:200px; height: 150px; ">',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: ' ',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: '(10+(5+20+2+40)*2=114)متنوع',
  },
  {
    question:
      '<img id="myImg" src="img/6.jpg" alt="Snow" style="width:200px; height: 150px; ">',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: ' ',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: '(20+3*4=32)متنوع',
  },
  {
    question:
      '<img id="myImg" src="img/7.jpg" alt="Snow" style="width:200px; height: 150px; ">',
    optionA: 'الاجابه صحيحه',
    optionB: 'الاجابه خطا',
    optionC: ' ',
    optionD: '',
    correctOption: 'optionA',
    infoQuest: '(1+20+4=25)متنوع',
  },
];
